---
apiVersion: v1
kind: Secret
metadata:
  name: loadmill-token
type: Opaque
data:
  token: MTIzNA==
# Ej: echo -n 1234 | base64
---
apiVersion: v1
kind: Service
metadata:
  name: loadmill-verify
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
    protocol: TCP
  selector:
    name: loadmill-verify
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadmill-verify
spec:
  selector:
    matchLabels:
      name: loadmill-verify
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        name: loadmill-verify
    spec:
      initContainers:
      - name: loadmill-token
        image: bash
        env:
        - name: LOADMILL_TOKEN
          valueFrom:
            secretKeyRef:
              name: loadmill-token
              key: token
        command: ['bash', '-c', 'mkdir -p /usr/share/nginx/html/loadmill-challenge; echo ${LOADMILL_TOKEN} > /usr/share/nginx/html/loadmill-challenge/${LOADMILL_TOKEN}.txt']
        volumeMounts:
          - name: loadmill-token
            mountPath: /usr/share/nginx/html/loadmill-challenge
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - name: loadmill-token
            mountPath: /usr/share/nginx/html/loadmill-challenge
      volumes:
      - name: loadmill-token
        emptyDir: {}
